# Generated by Django 2.2.13 on 2021-02-03 06:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user_admin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assessment_type',
            fields=[
                ('assessment_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_type', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('partner_org', models.CharField(blank=True, max_length=100, null=True)),
                ('sessions_count', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('student_count', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'batches',
            },
        ),
        migrations.CreateModel(
            name='entity',
            fields=[
                ('entity_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'entities',
            },
        ),
        migrations.CreateModel(
            name='entity_status',
            fields=[
                ('status', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, validators=[user_admin.models.validate_not_spaces])),
                ('entity', models.ForeignKey(default=user_admin.models.get_def, on_delete=django.db.models.deletion.CASCADE, to='user_admin.entity')),
            ],
            options={
                'verbose_name_plural': 'entity_statuses',
            },
        ),
        migrations.CreateModel(
            name='module_level',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=100, unique=True)),
                ('prerequisite', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('narrative', models.CharField(blank=True, max_length=100, null=True)),
                ('hint', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('assessment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.assessment_type')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.module_level')),
            ],
        ),
        migrations.CreateModel(
            name='question_content',
            fields=[
                ('question_content_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.FileField(upload_to='question_content')),
            ],
        ),
        migrations.CreateModel(
            name='question_type',
            fields=[
                ('question_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, validators=[user_admin.models.validate_not_spaces])),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('landline_number', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('enroll_date', models.DateField(blank=True, null=True)),
                ('dob', models.DateField()),
                ('address_1', models.CharField(max_length=100)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('languages', models.CharField(max_length=100)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(default='none.jpg', upload_to='student_images')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.entity_status')),
            ],
        ),
        migrations.CreateModel(
            name='student_module_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.module_level')),
                ('student_student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.student')),
            ],
        ),
        migrations.CreateModel(
            name='student_batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.batch')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.program')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.student')),
            ],
            options={
                'verbose_name_plural': 'student_batches',
            },
        ),
        migrations.CreateModel(
            name='question_option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_description', models.CharField(max_length=200)),
                ('is_right_option', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_admin.question_content'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.question_type'),
        ),
        migrations.CreateModel(
            name='program_module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=500, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.program')),
            ],
        ),
        migrations.AddField(
            model_name='module_level',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.program_module'),
        ),
        migrations.CreateModel(
            name='facilitator',
            fields=[
                ('facilitator_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('occupation', models.CharField(max_length=100)),
                ('specified_interests', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('landline_number', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('enroll_date', models.DateField(blank=True, null=True)),
                ('address_1', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=100)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(default='none.jpg', upload_to='facilitator_images')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.entity_status')),
            ],
        ),
        migrations.CreateModel(
            name='entity_type',
            fields=[
                ('entity_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, unique=True, validators=[user_admin.models.validate_not_spaces])),
                ('enitity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.entity')),
            ],
        ),
        migrations.CreateModel(
            name='center',
            fields=[
                ('center_id', models.AutoField(primary_key=True, serialize=False)),
                ('center_name', models.CharField(max_length=100, unique=True)),
                ('address_1', models.CharField(max_length=100)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('landline_number', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(max_length=100)),
                ('email_id', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('batch_check', models.BooleanField(default=False)),
                ('center_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.entity_type')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_incharge_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.facilitator'),
        ),
        migrations.AddField(
            model_name='batch',
            name='center_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.center'),
        ),
        migrations.AddField(
            model_name='batch',
            name='program_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.program'),
        ),
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.entity_status'),
        ),
    ]
