# Generated by Django 3.0.2 on 2020-04-04 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entity',
            fields=[
                ('entity_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='entity_status',
            fields=[
                ('status', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('enitity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.entity')),
            ],
        ),
        migrations.CreateModel(
            name='program',
            fields=[
                ('program_id', models.IntegerField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=100)),
                ('prerequisite', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('landline_number', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('enroll_date', models.DateField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('addeess_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('languages', models.CharField(max_length=100)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(default='none.jpg', upload_to='student_images')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.entity_status')),
            ],
        ),
        migrations.CreateModel(
            name='facilitator',
            fields=[
                ('facilitator_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(max_length=100)),
                ('specified_interests', models.CharField(max_length=100)),
                ('landline_number', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('enroll_date', models.DateField(blank=True, null=True)),
                ('addeess_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=100)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(default='none.jpg', upload_to='facilitator_images')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.entity_status')),
            ],
        ),
        migrations.CreateModel(
            name='entity_type',
            fields=[
                ('entity_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('enitity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.entity')),
            ],
        ),
        migrations.CreateModel(
            name='center',
            fields=[
                ('center_id', models.IntegerField(primary_key=True, serialize=False)),
                ('center_name', models.CharField(max_length=100)),
                ('addeess_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('landline_number', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('center_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.entity_status')),
            ],
        ),
    ]
