# Generated by Django 3.2.8 on 2021-10-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bulk_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(upload_to='bulk_upload/')),
            ],
        ),
        migrations.CreateModel(
            name='sync',
            fields=[
                ('syncid', models.AutoField(primary_key=True, serialize=False)),
                ('information_synchronized', models.CharField(max_length=150)),
                ('date_of_sync', models.DateTimeField(auto_now=True, null=True)),
                ('synchronization_type', models.CharField(choices=[('D', 'Download'), ('U', 'Upload')], max_length=10)),
            ],
        ),
    ]
