# Generated by Django 2.0.6 on 2021-09-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0002_bulk_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='sync',
            fields=[
                ('syncid', models.AutoField(primary_key=True, serialize=False)),
                ('information_synchronized', models.CharField(max_length=150)),
                ('date_of_sync', models.DateTimeField(auto_now=True, null=True)),
                ('synchronization_type', models.CharField(choices=[('D', 'Download'), ('U', 'Upload')], max_length=10)),
            ],
        ),
    ]
