# Generated by Django 3.0.2 on 2020-04-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0002_auto_20200404_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='addeess_1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='facilitator',
            old_name='addeess_1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='addeess_1',
            new_name='address_1',
        ),
        migrations.AddField(
            model_name='facilitator',
            name='password',
            field=models.CharField(default='creatingfuturesF', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='creatingfuturesS', max_length=100),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='center',
            name='center_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entity_type',
            name='entity_type_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='facilitator_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='module_level',
            name='level_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='program_module',
            name='module_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
