# Generated by Django 3.0.2 on 2020-04-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0003_auto_20200407_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity_status',
            name='enitity',
        ),
    ]
