# Generated by Django 3.0.5 on 2020-06-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0004_auto_20200626_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_option',
            name='option_description',
            field=models.CharField(max_length=200),
        ),
    ]
