# Generated by Django 3.0.2 on 2020-04-07 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0004_remove_entity_status_enitity'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='module_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.program_module'),
        ),
        migrations.AddField(
            model_name='questions',
            name='program_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.program'),
        ),
    ]
