# Generated by Django 2.0.6 on 2021-09-17 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0005_sync'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sync',
        ),
    ]
