# Generated by Django 3.0.2 on 2020-04-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0005_auto_20200407_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='module_id',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='program_id',
        ),
    ]
