# Generated by Django 3.0.5 on 2020-06-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0005_auto_20200626_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_option',
            name='is_right_option',
            field=models.BooleanField(default=False),
        ),
    ]
