# Generated by Django 3.0.2 on 2020-04-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0006_auto_20200407_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='partner_org',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
