# Generated by Django 3.0.5 on 2020-06-29 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0007_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testModel',
        ),
    ]
