# Generated by Django 3.0.2 on 2020-04-08 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0008_batch_student_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='module_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.program_module'),
        ),
        migrations.AddField(
            model_name='questions',
            name='program_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.program'),
        ),
    ]
