# Generated by Django 2.1.2 on 2020-12-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0009_auto_20200629_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_option',
            name='is_right_option',
            field=models.BooleanField(),
        ),
    ]
