# Generated by Django 3.0.2 on 2020-04-14 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0012_auto_20200414_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_batch',
            name='batch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.batch'),
        ),
        migrations.AlterField(
            model_name='student_batch',
            name='program_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.program'),
        ),
        migrations.AlterField(
            model_name='student_batch',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.student'),
        ),
        migrations.AlterField(
            model_name='student_module_level',
            name='module_level_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.module_level'),
        ),
        migrations.AlterField(
            model_name='student_module_level',
            name='student_student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.student'),
        ),
    ]
