# Generated by Django 3.0.2 on 2020-04-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0014_auto_20200414_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(),
        ),
    ]
