# Generated by Django 3.0.2 on 2020-04-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0015_auto_20200416_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module_level',
            name='level_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='module_level',
            name='level_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='program_module',
            name='module_name',
            field=models.CharField(max_length=100),
        ),
    ]
