# Generated by Django 3.0.2 on 2020-04-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0016_auto_20200417_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
