# Generated by Django 3.0.2 on 2020-04-20 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0019_auto_20200419_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='facilitator',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address_2',
        ),
    ]
