# Generated by Django 3.0.2 on 2020-04-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0020_auto_20200420_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'F')], max_length=1),
        ),
    ]
