# Generated by Django 3.0.2 on 2020-04-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0022_auto_20200421_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
