# Generated by Django 3.0.2 on 2020-04-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0023_auto_20200423_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='batch_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('Multiple Choice', 'Multiple Choice')], max_length=100),
        ),
    ]
