# Generated by Django 3.0.2 on 2020-04-28 14:07

from django.db import migrations, models
import django.db.models.deletion
import user_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0027_auto_20200427_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity_status',
            name='enitity',
            field=models.ForeignKey(default=user_admin.models.get_def, on_delete=django.db.models.deletion.CASCADE, to='user_admin.entity'),
        ),
    ]
