# Generated by Django 3.0.2 on 2020-04-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0029_auto_20200428_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity_status',
            old_name='enitity',
            new_name='entity',
        ),
    ]
