# Generated by Django 3.0.2 on 2020-05-01 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0031_student_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_status',
        ),
    ]
