# Generated by Django 3.0.3 on 2020-05-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0033_auto_20200508_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='option1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
