# Generated by Django 3.0.2 on 2020-05-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0036_image_question_images_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_question',
            name='question_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
