# Generated by Django 3.0.2 on 2020-05-15 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0038_auto_20200515_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='av_question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.FileField(upload_to='question_av')),
                ('question_type', models.CharField(choices=[('Video', 'Video'), ('Audio', 'Audio')], max_length=100)),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.module_level')),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.program_module')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.program')),
            ],
        ),
    ]
