# Generated by Django 3.0.2 on 2020-05-15 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0039_av_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='av_sub_question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100, unique=True)),
                ('answer', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('Multiple Choice', 'Multiple Choice')], max_length=100)),
                ('option1', models.CharField(blank=True, max_length=100, null=True)),
                ('option2', models.CharField(blank=True, max_length=100, null=True)),
                ('option3', models.CharField(blank=True, max_length=100, null=True)),
                ('option4', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('av', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.av_question')),
            ],
        ),
    ]
