# Generated by Django 3.0.2 on 2020-05-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0040_av_sub_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_question',
            name='option1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='image_question',
            name='option2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='image_question',
            name='option3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='image_question',
            name='option4',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='images_question',
            name='option1',
            field=models.ImageField(upload_to='question_image_2'),
        ),
        migrations.AlterField(
            model_name='images_question',
            name='option2',
            field=models.ImageField(upload_to='question_image_2'),
        ),
        migrations.AlterField(
            model_name='images_question',
            name='option3',
            field=models.ImageField(upload_to='question_image_2'),
        ),
        migrations.AlterField(
            model_name='images_question',
            name='option4',
            field=models.ImageField(upload_to='question_image_2'),
        ),
    ]
