# Generated by Django 3.0.2 on 2020-05-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0041_auto_20200525_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_question',
            name='question_text',
            field=models.CharField(default='asd', max_length=500),
        ),
    ]
