# Generated by Django 3.0.3 on 2020-06-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0043_auto_20200525_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='av_sub_question',
            name='option1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='av_sub_question',
            name='option2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='av_sub_question',
            name='option3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='av_sub_question',
            name='option4',
            field=models.CharField(max_length=100),
        ),
    ]
