# Generated by Django 3.0.5 on 2021-01-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0002_assessment_type'),
        ('user_student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='scores',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_score', models.IntegerField()),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.IntegerField(default=0)),
                ('assesment_type', models.CharField(default='Narrative', max_length=20)),
                ('assessment_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_admin.assessment_type')),
                ('batch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.batch')),
                ('level_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.module_level')),
                ('question_content_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_admin.question_content')),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.student')),
            ],
        ),
    ]
