# Generated by Django 2.2.13 on 2021-01-23 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_student', '0002_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scores',
            name='assesment_type',
        ),
    ]
