# Generated by Django 2.2.13 on 2021-01-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_student', '0003_remove_scores_assesment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='question_content_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
