-- MySQL Script generated by MySQL Workbench
-- Tue Mar 24 23:58:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`entity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entity` (
  `entity` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`entity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entity_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entity_status` (
  `entity` VARCHAR(50) NOT NULL,
  `status` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`status`),
  INDEX `fk_status_entity_idx` (`entity` ASC) VISIBLE,
  CONSTRAINT `fk_status_entity`
    FOREIGN KEY (`entity`)
    REFERENCES `mydb`.`entity` (`entity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `second_name` VARCHAR(100) NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `status` INT NOT NULL,
  `landline_number` VARCHAR(45) NULL,
  `mobile_number` VARCHAR(45) NULL,
  `dob` VARCHAR(45) NULL,
  `email_id` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(1) NULL,
  `address` VARCHAR(200) NULL,
  `enrollment_date` DATE NULL,
  `occupation` VARCHAR(45) NULL,
  `class` VARCHAR(45) NULL,
  `school` VARCHAR(45) NULL,
  `languages_known` VARCHAR(45) NULL,
  `comments` VARCHAR(45) NULL,
  `created_date` DATE NULL,
  `updated_date` DATE NULL,
  `created_by` VARCHAR(45) NULL,
  `updated_by` VARCHAR(45) NULL,
  `image` BLOB NULL,
  PRIMARY KEY (`student_id`),
  INDEX `fk_student_status_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `fk_student_status`
    FOREIGN KEY (`status`)
    REFERENCES `mydb`.`entity_status` (`status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`facilitator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`facilitator` (
  `facilitator_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `second_name` VARCHAR(45) NULL,
  `email_id` VARCHAR(45) NULL,
  `dob` DATE NULL,
  `mobile_number` VARCHAR(45) NULL,
  `occupation` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `languages_known` VARCHAR(45) NULL,
  `status` INT NOT NULL,
  `enrolled_date` DATE NULL,
  `specific_interests` VARCHAR(300) NULL,
  `comments` VARCHAR(500) NULL,
  `created_date` DATE NULL,
  `updated_date` DATE NULL,
  `created_by` VARCHAR(45) NULL,
  `updated_by` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `admin` VARCHAR(1) NULL,
  PRIMARY KEY (`facilitator_id`),
  INDEX `fk_facilitator_status_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `fk_facilitator_status`
    FOREIGN KEY (`status`)
    REFERENCES `mydb`.`entity_status` (`status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`program`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`program` (
  `program_id` INT NOT NULL AUTO_INCREMENT,
  `program_name` VARCHAR(45) NULL,
  `prerequisite` VARCHAR(45) NULL,
  `comments` VARCHAR(45) NULL,
  `created_date` DATE NULL,
  `updated_date` DATE NULL,
  `created_by` VARCHAR(45) NULL,
  `updated_by` VARCHAR(45) NULL,
  PRIMARY KEY (`program_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entity_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entity_type` (
  `entity` VARCHAR(50) NOT NULL,
  `entity_type_id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  INDEX `fk_entity_type_entity1_idx` (`entity` ASC) VISIBLE,
  PRIMARY KEY (`entity_type_id`, `entity`),
  CONSTRAINT `fk_entity_type_entity1`
    FOREIGN KEY (`entity`)
    REFERENCES `mydb`.`entity` (`entity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`center` (
  `center_id` INT NOT NULL AUTO_INCREMENT,
  `center_name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `comments` VARCHAR(45) NULL,
  `contact_person` VARCHAR(45) NULL,
  `email_id` VARCHAR(45) NULL,
  `mobile_number` VARCHAR(45) NULL,
  `center_type_id` INT NOT NULL,
  PRIMARY KEY (`center_id`),
  INDEX `fk_center_entity_type_idx` (`center_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_center_entity_type`
    FOREIGN KEY (`center_type_id`)
    REFERENCES `mydb`.`entity_type` (`entity_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`batch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`batch` (
  `batch_id` INT NOT NULL AUTO_INCREMENT,
  `program_id` INT NOT NULL,
  `batch_name` VARCHAR(45) NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `status` INT NOT NULL,
  `batch_incharge_id` INT NOT NULL,
  `center_id` INT NOT NULL,
  `sessions_count` INT NULL,
  `comments` VARCHAR(45) NULL,
  `created_date` DATE NULL,
  `updated_date` DATE NULL,
  `created_by` VARCHAR(45) NULL,
  `updated_by` VARCHAR(45) NULL,
  PRIMARY KEY (`batch_id`, `program_id`),
  INDEX `fk_batch_program_idx` (`program_id` ASC) VISIBLE,
  INDEX `fk_batch_center_idx` (`center_id` ASC) VISIBLE,
  INDEX `fk_batch_status_idx` (`status` ASC) VISIBLE,
  INDEX `fk_batch_facilitator_idx` (`batch_incharge_id` ASC) VISIBLE,
  CONSTRAINT `fk_batch_program`
    FOREIGN KEY (`program_id`)
    REFERENCES `mydb`.`program` (`program_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_batch_center`
    FOREIGN KEY (`center_id`)
    REFERENCES `mydb`.`center` (`center_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_batch_status`
    FOREIGN KEY (`status`)
    REFERENCES `mydb`.`entity_status` (`status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_batch_facilitator`
    FOREIGN KEY (`batch_incharge_id`)
    REFERENCES `mydb`.`facilitator` (`facilitator_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`program_module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`program_module` (
  `module_id` INT NOT NULL AUTO_INCREMENT,
  `module_name` VARCHAR(45) NOT NULL,
  `program_id` INT NOT NULL,
  PRIMARY KEY (`module_id`, `program_id`),
  INDEX `fk_program_module_program1_idx` (`program_id` ASC) VISIBLE,
  CONSTRAINT `fk_program_module_program1`
    FOREIGN KEY (`program_id`)
    REFERENCES `mydb`.`program` (`program_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`module_level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`module_level` (
  `level_id` INT NOT NULL AUTO_INCREMENT,
  `module_id` INT NOT NULL,
  `level_number` INT NOT NULL,
  `level_description` VARCHAR(45) NULL,
  PRIMARY KEY (`level_id`),
  INDEX `fk_module_level_program_module1_idx` (`module_id` ASC) VISIBLE,
  UNIQUE INDEX `module_level_UNIQUE` (`module_id` ASC, `level_number` ASC) INVISIBLE,
  CONSTRAINT `fk_module_level_program_module1`
    FOREIGN KEY (`module_id`)
    REFERENCES `mydb`.`program_module` (`module_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`questions` (
  `question_id` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(200) NULL,
  `answer` VARCHAR(500) NULL,
  `level_id` INT NULL,
  `question_type` VARCHAR(45) NULL,
  `narrative` VARCHAR(45) NULL,
  `option1` VARCHAR(45) NULL,
  `option2` VARCHAR(45) NULL,
  `option3` VARCHAR(45) NULL,
  `option4` VARCHAR(45) NULL,
  `comments` VARCHAR(45) NULL,
  `created_date` DATE NULL,
  `updated_date` DATE NULL,
  `created_by` VARCHAR(45) NULL,
  `updated_by` VARCHAR(45) NULL,
  `image` BLOB NULL,
  `video_location` VARCHAR(200) NULL,
  PRIMARY KEY (`question_id`),
  INDEX `fk_questions_module_level1_idx` (`level_id` ASC) VISIBLE,
  CONSTRAINT `fk_questions_module_level1`
    FOREIGN KEY (`level_id`)
    REFERENCES `mydb`.`module_level` (`level_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student_module_level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student_module_level` (
  `student_student_id` INT NOT NULL,
  `module_level_id` INT NOT NULL,
  PRIMARY KEY (`student_student_id`, `module_level_id`),
  INDEX `fk_student_module_level_student1_idx` (`student_student_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_module_level_module_level1`
    FOREIGN KEY (`module_level_id`)
    REFERENCES `mydb`.`module_level` (`level_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_module_level_student1`
    FOREIGN KEY (`student_student_id`)
    REFERENCES `mydb`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student_batches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student_batches` (
  `student_id` INT NOT NULL,
  `batch_id` INT NOT NULL,
  `program_id` INT NOT NULL,
  PRIMARY KEY (`student_id`, `batch_id`, `program_id`),
  INDEX `fk_student_has_batch_batch1_idx` (`batch_id` ASC, `program_id` ASC) VISIBLE,
  INDEX `fk_student_has_batch_student1_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_batch_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_batch_batch1`
    FOREIGN KEY (`batch_id` , `program_id`)
    REFERENCES `mydb`.`batch` (`batch_id` , `program_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
