# Generated by Django 2.2.13 on 2021-01-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assessment_type',
            fields=[
                ('assessment_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_type', models.TextField()),
            ],
        ),
    ]
