# Generated by Django 2.2.13 on 2021-01-13 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_student', '0002_assessment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scores',
            name='id',
        ),
        migrations.AddField(
            model_name='scores',
            name='assessment_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_student.assessment_type'),
        ),
        migrations.AddField(
            model_name='scores',
            name='score_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
