# Generated by Django 2.1.2 on 2020-12-08 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0010_auto_20201202_1748'),
        ('user_student', '0002_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='assesment_type',
            field=models.CharField(default='Narrative', max_length=20),
        ),
        migrations.AddField(
            model_name='score',
            name='batch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.batch'),
        ),
        migrations.AddField(
            model_name='score',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='level_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.module_level'),
        ),
        migrations.AddField(
            model_name='score',
            name='question_content_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_admin.question_content'),
        ),
        migrations.AddField(
            model_name='score',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.student'),
        ),
        migrations.AddField(
            model_name='score',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
