# Generated by Django 2.0.6 on 2021-09-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_student', '0003_auto_20210203_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='updated_by',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
