# Generated by Django 3.1.12 on 2021-08-12 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0001_initial'),
        ('user_student', '0003_auto_20210203_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='skillmaster',
            fields=[
                ('skillid', models.IntegerField(primary_key=True, serialize=False)),
                ('skillname', models.CharField(max_length=30)),
                ('skilltype', models.CharField(max_length=20)),
                ('skilldescription', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Skillmaster',
            },
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('student_skill_id', models.IntegerField(primary_key=True, serialize=False)),
                ('skillid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_student.skillmaster')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.student')),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
    ]
