# Generated by Django 2.2.13 on 2021-01-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_student', '0004_auto_20210113_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='score_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
