# Generated by Django 2.0.6 on 2021-09-17 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_student', '0004_scores_updated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scores',
            old_name='updated_by',
            new_name='updated_date',
        ),
    ]
