# Generated by Django 2.0.6 on 2021-09-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_student', '0005_auto_20210917_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
