# Generated by Django 3.0.2 on 2020-04-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='lastnamee',
            new_name='lastname',
        ),
    ]
