# Generated by Django 3.0.2 on 2020-04-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200402_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
